app = "aura-command-backend"
primary_region = "bom"

[build]
  dockerfile = "server/Dockerfile"
  ignorefile = "server/.dockerignore"

[env]
  MEDIASOUP_RTC_MIN_PORT = "40000"
  MEDIASOUP_RTC_MAX_PORT = "40020"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "udp"
  internal_port = 40000
  [[services.ports]]
    port = 40000

[[services]]
  protocol = "udp"
  internal_port = 40001
  [[services.ports]]
    port = 40001

[[services]]
  protocol = "udp"
  internal_port = 40002
  [[services.ports]]
    port = 40002

[[services]]
  protocol = "udp"
  internal_port = 40003
  [[services.ports]]
    port = 40003

[[services]]
  protocol = "udp"
  internal_port = 40004
  [[services.ports]]
    port = 40004

[[services]]
  protocol = "udp"
  internal_port = 40005
  [[services.ports]]
    port = 40005

[[services]]
  protocol = "udp"
  internal_port = 40006
  [[services.ports]]
    port = 40006

[[services]]
  protocol = "udp"
  internal_port = 40007
  [[services.ports]]
    port = 40007

[[services]]
  protocol = "udp"
  internal_port = 40008
  [[services.ports]]
    port = 40008

[[services]]
  protocol = "udp"
  internal_port = 40009
  [[services.ports]]
    port = 40009

[[services]]
  protocol = "udp"
  internal_port = 40010
  [[services.ports]]
    port = 40010

[[services]]
  protocol = "udp"
  internal_port = 40011
  [[services.ports]]
    port = 40011

[[services]]
  protocol = "udp"
  internal_port = 40012
  [[services.ports]]
    port = 40012

[[services]]
  protocol = "udp"
  internal_port = 40013
  [[services.ports]]
    port = 40013

[[services]]
  protocol = "udp"
  internal_port = 40014
  [[services.ports]]
    port = 40014

[[services]]
  protocol = "udp"
  internal_port = 40015
  [[services.ports]]
    port = 40015

[[services]]
  protocol = "udp"
  internal_port = 40016
  [[services.ports]]
    port = 40016

[[services]]
  protocol = "udp"
  internal_port = 40017
  [[services.ports]]
    port = 40017

[[services]]
  protocol = "udp"
  internal_port = 40018
  [[services.ports]]
    port = 40018

[[services]]
  protocol = "udp"
  internal_port = 40019
  [[services.ports]]
    port = 40019

[[services]]
  protocol = "udp"
  internal_port = 40020
  [[services.ports]]
    port = 40020

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
