import User from "./models/User.js";
import Channel from "./models/Channel.js";
import Room from "./models/Room.js";

const rooms = new Map(), users = new Map();

/**
 * @param {import("socket.io").Socket} socket
 * @param {import("socket.io").Server} io
 */
export default function registerSocketEventHandlers (socket, io) {
    // deviceId: uuid generated by the device
    // displayName: displayName of the user
    socket.on("createRoom", ({deviceId, displayName}) => {
        let roomId;
        do {
            roomId = Room.generateRoomId();
        } while (rooms.has(roomId));

        const room = new Room(roomId, deviceId);
        rooms.set(roomId, room);

        const user = new User(displayName, deviceId, roomId);
        users.set(deviceId, user);

        socket.join(roomId);
        socket.emit("roomJoined", room);

        console.log(displayName, deviceId, "created a room ", roomId);
    });

    socket.on("joinRoom", ({deviceId, displayName, roomId}) => {
        if (!rooms.has(roomId)) {
            socket.emit("error", { message: "Room not found" });
            console.log(displayName, deviceId, "failed to join room", roomId, "(not found)");
            return;
        }

        const room = rooms.get(roomId);
        room.addMember(deviceId);

        const user = new User(displayName, deviceId, roomId);
        users.set(deviceId, user);

        socket.join(roomId);
        socket.emit("roomJoined", room);

        console.log(displayName, deviceId, "joined room", roomId);
    });
}