import User from "./models/User";
import Channel from "./models/Channel";
import Room from "./models/Room";

const rooms = new Map(), users = new Map();

/**
 * @param {import("socket.io").Socket} socket
 * @param {import("socket.io").Server} io
 */
export default function registerSocketEventHandlers (socket, io) {
    // deviceId: uuid generated by the device
    // displayName: displayName of the user
    socket.on("createRoom", ({deviceId, displayName}) => {
        const roomId = Room.generateRoomId();
        const room = new Room(id, deviceId);
    });
}